# Generated by Django 5.1.4 on 2025-01-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
