# Generated by Django 5.1.4 on 2025-01-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='semester',
            field=models.IntegerField(default=2),
        ),
    ]
